### ISSUE TITLE
Circular Structure to JSON error

### ISSUE THREAD

**Issue by Sharlaan** [Gossamer-React/Lucid#133]
Setup :
- Windows 10
- Node 11.6
- CRA with React v16.7.0-alpha.2

No Graphql or Apollo yet, just a simple React counter with hooks `useState` and `useEffect`.

Result :
![](https://i.imgur.com/v6ByWaV.png)

Please ask me anything to help resolve this bug.

**Comment by neyser95** [comment]
Thank you for bring this to our attention. This is something we're currently looking at. It seems that some applications tend to have this circular structure error. We are currently looking at this and we'll try to update it as soon as we've figured it out. 👍.

**Comment by neyser95** [comment]
This issue will continue at #137.
