### ISSUE TITLE
Does this work with React Native

### ISSUE THREAD

**Issue by bsbechtel** [Gossamer-React/Lucid#140]
Does this work with a React Native + Apollo Client app? Given you need the independent react devtools, I'm guessing no?

**Comment by neyser95** [comment]
@bsbechtel This has not been tested for react native so it most likely would not work as we use React devtool to gain access to an application's fiber object. This is something we can test for later in the upcoming months.

**Comment by bsbechtel** [comment]
That would be great if you could! If it does end up working, can you add a comment to this repo so I get a notification? I'll close it for now then. Thanks!
